from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from agents.synthesis_agent import ReadinessReport


def render_markdown(report: ReadinessReport) -> str:
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    must_clarify, should_clarify = _split_product_gaps(report.product_gaps)
    lines = [
        "# 🚦 Ready4Codex Report",
        "",
        f"**Generated:** {timestamp}",
        "",
        f"**Repository:** {report.repository}",
        "",
        f"**Feature:** {report.feature}",
        "",
        _verdict_banner(report.score),
        "",
        f"`{_score_bar(report.score)} {report.score}/100`",
        "",
        "## 🔴 Must Clarify",
        "",
        _markdown_list(must_clarify),
        "",
        "## 🟡 Should Clarify",
        "",
        _markdown_list(should_clarify),
        "",
        "## ⚙️ Engineering Risks",
        "",
        _markdown_list(report.engineering_risks),
        "",
        "## 🏗️ Architecture Fit",
        "",
        _markdown_dict(report.architecture_fit),
        "",
        "## 🧪 Testability Analysis",
        "",
        _markdown_dict(report.testability_analysis),
        "",
        "## 🤖 Suggested Agent Plan",
        "",
        _markdown_agent_plan(report.suggested_agent_plan),
        "",
        "## 📋 Codex-Ready Prompt",
        "",
        "> 💡 Copy and paste this directly into Codex",
        "",
        "```text",
        report.codex_ready_prompt,
        "```",
        "",
        "## ⚠️ Repo Health Warnings",
        "",
        _markdown_list(report.repo_health_warnings),
        "",
        "## 📚 Architecture Summary",
        "",
        _markdown_dict(report.architecture_summary),
        "",
        "## 🔎 Inspected Files",
        "",
        _markdown_list(report.inspected_files),
        "",
        "---",
        "",
        "*Generated by Ready4Codex —",
        "The quality gate before agentic development*",
    ]
    return "\n".join(lines)


def save_report(report: ReadinessReport, output_dir: str = "reports") -> Path:
    directory = Path(output_dir)
    directory.mkdir(parents=True, exist_ok=True)
    slug = _slugify(f"{report.repository}-{report.feature}")[:80]
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    path = directory / f"{timestamp}-{slug}.md"
    path.write_text(render_markdown(report), encoding="utf-8")
    return path


def _markdown_list(items: list[str]) -> str:
    if not items:
        return "- None"
    return "\n".join(f"- {item}" for item in items)


def _verdict_banner(score: int) -> str:
    if score >= 80:
        return f"## ✅ READY — {score}/100"
    if score >= 50:
        return f"## ⚠️ NEEDS WORK — {score}/100"
    return f"## ❌ NOT READY — {score}/100"


def _score_bar(score: int) -> str:
    bounded_score = max(0, min(100, score))
    filled = round(bounded_score / 5)
    empty = 20 - filled
    return f"{'█' * filled}{'░' * empty}"


def _split_product_gaps(items: list[str]) -> tuple[list[str], list[str]]:
    must_clarify: list[str] = []
    should_clarify: list[str] = []
    for item in items:
        if _sounds_non_blocking(item):
            should_clarify.append(item)
        else:
            must_clarify.append(item)
    return must_clarify, should_clarify


def _sounds_non_blocking(item: str) -> bool:
    value = item.lower()
    markers = (
        "should",
        "could",
        "can users",
        "later",
        "confirm",
        "preference",
        "preferences",
    )
    return any(marker in value for marker in markers)


def _markdown_dict(value: dict[str, object]) -> str:
    if not value:
        return "- None"
    lines = []
    for key, item in value.items():
        if isinstance(item, list):
            lines.append(f"- {key}:")
            if item:
                lines.extend(f"  - {entry}" for entry in item)
            else:
                lines.append("  - None")
        else:
            lines.append(f"- {key}: {item}")
    return "\n".join(lines)


def _markdown_agent_plan(plan: list[dict[str, object]]) -> str:
    if not plan:
        return "- None"
    lines: list[str] = []
    for item in plan:
        lines.append(f"### {item.get('agent', 'Agent')}")
        lines.append("")
        lines.append(str(item.get("responsibility", "Unspecified responsibility")))
        lines.append("")
        lines.append("Files:")
        files = item.get("files", [])
        if isinstance(files, list) and files:
            lines.extend(f"- {path}" for path in files)
        else:
            lines.append("- None")
        lines.append("")
    return "\n".join(lines).rstrip()


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug or "ready4codex-report"
